# Generated by Django 2.0 on 2018-06-26 07:05

import app.todo.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255, verbose_name='Task Name')),
                ('color', models.CharField(default='#ffffff', max_length=7, validators=[app.todo.validators.HexadecimalValidator], verbose_name='Color Label')),
                ('done', models.BooleanField(default=False, verbose_name='Task Status')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Archival Status')),
                ('timestamp', models.DateTimeField(auto_now=True, verbose_name='Created Time')),
            ],
        ),
    ]
